name: cdr
channels:
  - defaults
dependencies:
  - pip
  - python>=3,<3.12
  - pip:
    - dash
    - matplotlib
    - numpy>=1.9
    - pandas>=1.1
    - pyyaml
    - scikit-learn
    - scipy>=0.14
    - tensorflow>=1.9
    - tensorflow-probability
